name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: create build dir
      run: if [ ! -d build ]; then mkdir build 
      
    - name: build all binaries
      run: make
